name: "Test"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Test Resolve"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10, 22]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
