name: "Test"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Test Resolve"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18, 20, 22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
